int acertou();
void abertura();
void chuta();
int jachutou(char letra);
void desenhaforca();
void escolhepalavra();
int enforcou();
void adicionaPalavra();
int numChutesErrados();
int letraExiste(char letra);
int verificaChute(char chute);
void escolheNivel();
int ganhou();
void pontuac();
void ranking();
int contemPalavra(char* palavraNova);
void colocarPalavra();
void regrasDoJogo();
void verificarRankin();
void finalDoJogo();
void sairDoJogo();
void adicionapalavra();